# -*- coding: utf-8 -*-
"""Copy of project_innovative.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14GLJaXka1C59bGhQ5MdZsv4KXEZOXnE8

analysis
"""

# =========================================================
# RESEARCH PROJECT: Banglish Sentiment Analysis Pipeline
# AUTHORS: Monjeeta Sinha Roy & Shantanu Santra (IEM)
# =========================================================

# 1. Environment Setup
!pip install phonetic-bangla transformers torch tqdm nltk scikit-learn

import pandas as pd
import nltk
import re
from phoneticbn import bn
from transformers import pipeline
from tqdm import tqdm
from sklearn.metrics import classification_report, f1_score

print("Setting up NLTK English Dictionary...")
nltk.download('words', quiet=True)
from nltk.corpus import words
english_dict = set(words.words())

def smart_normalizer(text):
    raw_words = str(text).split()
    final_sentence = []
    for word in raw_words:
        clean_word = re.sub(r'[^\w\s]', '', word.lower())
        if clean_word in english_dict and len(clean_word) > 2:
            final_sentence.append(word)
        else:
            final_sentence.append(bn(word))
    return " ".join(final_sentence)

# 2. Dataset Processing
FILE_NAME = 'final_kolkata_banglish_dataset.csv'
df = pd.read_csv(FILE_NAME)
print(f"✅ Loaded {len(df)} rows from {FILE_NAME}")

print("Phase 1 & 2: Generating Normalizations (Phonetic & Smart)...")
df['Naive_Text'] = df['text'].apply(lambda x: bn(str(x)))
df['Smart_Text'] = df['text'].apply(smart_normalizer)

# 3. AI Evaluation
print("Loading Native Bengali AI Engine...")
sentiment_ai = pipeline("text-classification", model="tabularisai/multilingual-sentiment-analysis")

raw_correct = 0
naive_correct = 0
smart_correct = 0
total_rows = len(df)

# ---> THE TRACKING LISTS ARE RIGHT HERE IN THE SAME CELL <---
true_labels = []
raw_predictions = []
naive_predictions = []
smart_predictions = []

print(f"🚀 Running Full Evaluation on {total_rows} rows. Please wait...")
for index, row in tqdm(df.iterrows(), total=total_rows):
    # Added .strip() to fix the NaN error by removing invisible spaces!
    label = str(row['sentiment']).lower().strip()

    raw_p = sentiment_ai(str(row['text']), truncation=True)[0]['label'].lower().strip()
    naive_p = sentiment_ai(str(row['Naive_Text']), truncation=True)[0]['label'].lower().strip()
    smart_p = sentiment_ai(str(row['Smart_Text']), truncation=True)[0]['label'].lower().strip()

    if label == raw_p: raw_correct += 1
    if label == naive_p: naive_correct += 1
    if label == smart_p: smart_correct += 1

    true_labels.append(label)
    raw_predictions.append(raw_p)
    naive_predictions.append(naive_p)
    smart_predictions.append(smart_p)

# 4. Results Generation (Accuracy)
raw_acc = (raw_correct / total_rows) * 100
naive_acc = (naive_correct / total_rows) * 100
smart_acc = (smart_correct / total_rows) * 100

print("\n" + "="*50)
print("🏆 FINAL RESEARCH STATISTICS 🏆")
print("="*50)
print(f"1. RAW Accuracy:           {raw_acc:.2f}%")
print(f"2. NAIVE Accuracy:         {naive_acc:.2f}% (Case 1)")
print(f"3. SMART Accuracy:        {smart_acc:.2f}% (Case 2)")
print("-" * 50)
print(f"Naive vs. Smart Improvement: {smart_acc - naive_acc:.2f}%")
print("="*50)

# 5. The F1-Scores and Tables (Happening instantly at the end!)
print("\n📊 EXTENDED METRICS 📊")

# zero_division=0 prevents any math errors if the dataset has weird labels
f1_naive = f1_score(true_labels, naive_predictions, average='weighted', zero_division=0)
f1_smart = f1_score(true_labels, smart_predictions, average='weighted', zero_division=0)

print(f"Phase 2 (Naive) Weighted F1-Score: {f1_naive:.4f}")
print(f"Phase 3 (Smart) Weighted F1-Score: {f1_smart:.4f}")

print("\n=== PHASE 2: NAIVE NORMALIZER METRICS ===")
print(classification_report(true_labels, naive_predictions, digits=4, zero_division=0))

print("\n=== PHASE 3: SMART FILTER METRICS ===")
print(classification_report(true_labels, smart_predictions, digits=4, zero_division=0))